export interface SalesInfoDetail {
    displayOptionIndex: number;
    sortFieldOptionIndex: number;
    codeDescription: string | null;
    lstSalesInfoDetailGrid: SalesInfoDetailGrid[];
    lstCustomizedTableGrid: CustomizedTableGrid[];
    lstSalesInfoDetailGridColumnHeaders: any | null; // Replace 'any' with the appropriate type if known
    lstPieChartValues: any | null; // Replace 'any' with the appropriate type if known
    sSubDetailType: string;
    isDirty: boolean;
    isNew: boolean;
    totalCount: number;
    createdBy: string | null;
    createdDate: string;
    lastModifiedBy: string | null;
    lastModifiedDate: string;
    primaryDist: string | null;
    rowCount: number;
}

export interface SalesInfoDetailGrid {
    brand: string | null;
    description: string | null;
    catlogCode: string | null;
    customerCode: string | null;
    customerName: string | null;
    repCode: string | null;
    repName: string | null;
    stateCode: string | null;
    stateName: string | null;
    busArea: string | null;
    market: string | null;
    catGroup: string | null;
    catSubGroup: string | null;
    parentCustomer: string | null;
    conversion: string | null;
    code: string;
    md: string;
    sum1: number;
    sum2: number;
    sum3: number;
    sum4: number;
    sum5: number;
    sum6: number;
    sum7: number;
    sum8: number;
    sum9: number;
    sum10: number;
    sum11: number;
    sum12: number;
    sum13: number;
    sum14: number;
    sum15: number;
    sum16: number;
    sum17: number;
    sum18: number;
    col1: string | null;
    col2: string | null;
    col3: string | null;
    col4: string | null;
    col5: string | null;
    col6: string | null;
    col7: string | null;
    col8: string | null;
    col9: string | null;
    col10: string | null;
    dollar1: number;
    dollar2: number;
    dollar3: number;
    dollar4: number;
    dollar5: number;
    dollar6: number;
    tonnes1: number;
    tonnes2: number;
    tonnes3: number;
    tonnes4: number;
    tonnes5: number;
    tonnes6: number;
    volYear1: number;
    volYear2: number;
    volYear3: number;
    valYear1: number;
    valYear2: number;
    valYear3: number;
    displayOption: string;
    sum1Tot: number;
    sum2Tot: number;
    sum3Tot: number;
    sum4Tot: number;
    sum5Tot: number;
    sum6Tot: number;
    sum7Tot: number;
    sum8Tot: number;
    sum9Tot: number;
    sum10Tot: number;
    sum11Tot: number;
    sum12Tot: number;
    sum13Tot: number;
    sum14Tot: number;
    sum15Tot: number;
    sum16Tot: number;
    volYear1Tot: number;
    volYear2Tot: number;
    volYear3Tot: number;
    valYear1Tot: number;
    valYear2Tot: number;
    valYear3Tot: number;
    sum_m12: number;
    sum_m11: number;
    sum_m10: number;
    sum_m09: number;
    sum_m08: number;
    sum_m07: number;
    sum_m06: number;
    sum_m05: number;
    sum_m04: number;
    sum_m03: number;
    sum_m02: number;
    sum_m01: number;
    sum_m12Tot: number;
    sum_m11Tot: number;
    sum_m10Tot: number;
    sum_m09Tot: number;
    sum_m08Tot: number;
    sum_m07Tot: number;
    sum_m06Tot: number;
    sum_m05Tot: number;
    sum_m04Tot: number;
    sum_m03Tot: number;
    sum_m02Tot: number;
    sum_m01Tot: number;
    sum_m11_unitsTot: number;
    sum_m09_unitsTot: number;
    sum_m07_unitsTot: number;
    sum_m05_unitsTot: number;
    sum_m03_unitsTot: number;
    sum_m01_unitsTot: number;
    sum2_unitsTot: number;
    sum4_unitsTot: number;
    sum6_unitsTot: number;
    sum8_unitsTot: number;
    sum10_unitsTot: number;
    sum12_unitsTot: number;
    sum13_unitsTot: number;
    sum15_unitsTot: number;
    vol_yr1_unitsTot: number;
    vol_yr2_unitsTot: number;
    vol_yr3_unitsTot: number;
    currentMonthBudget: number;
    currentMonthBudgetT: number;
    currentMonthBudgetU: number;
    budgetYTD: number;
    currentMonthBudgetTot: number;
    currentMonthBudgetTTot: number;
    currentMonthBudgetUTot: number;
    budgetYTDTot: number;
    budgetYTD_TTot: number;
    budgetYTD_UTot: number;
}

export interface CustomizedTableGrid {
    mc: string;
    m1D: number;
    m1T: number;
    m1U: number;
    m2D: number;
    m2T: number;
    m2U: number;
    m3D: number;
    m3T: number;
    m3U: number;
    m4D: number;
    m4T: number;
    m4U: number;
    m5D: number;
    m5T: number;
    m5U: number;
    m6D: number;
    m6T: number;
    m6U: number;
    mtd: number;
    mtt: number;
    mtu: number;
    md: string;
    mtytdd: number;
    mtytdt: number;
    mtytdu: number;
    mlytdd: number;
    mlytdt: number;
    mlytdu: number;
    mpd: number;
    mpt: number;
    mpu: number;
    mY1D: number;
    mY1T: number;
    mY1U: number;
    mY2D: number;
    mY2T: number;
    mY2U: number;
    mY3D: number;
    mY3T: number;
    mY3U: number;
    m1DTot: number;
    m1TTot: number;
    m1UTot: number;
    m2DTot: number;
    m2TTot: number;
    m2UTot: number;
    m3DTot: number;
    m3TTot: number;
    m3UTot: number;
    m4DTot: number;
    m4TTot: number;
    m4UTot: number;
    m5DTot: number;
    m5TTot: number;
    m5UTot: number;
    m6DTot: number;
    m6TTot: number;
    m6UTot: number;
    mtdTot: number;
    mttTot: number;
    mtuTot: number;
    mtytddTot: number;
    mtytdtTot: number;
    mtytduTot: number;
    mlytddTot: number;
    mlytdtTot: number;
    mlytduTot: number;
    mpdTot: number;
    mptTot: number;
    mpuTot: number;
    mY1DTot: number;
    mY1TTot: number;
    mY1UTot: number;
    mY2DTot: number;
    mY2TTot: number;
    mY2UTot: number;
    mY3DTot: number;
    mY3TTot: number;
    mY3UTot: number;
    mdTot: number;
    m_m1D: number;
    m_m1T: number;
    m_m1U: number;
    m_m2D: number;
    m_m2T: number;
    m_m2U: number;
    m_m3D: number;
    m_m3T: number;
    m_m3U: number;
    m_m4D: number;
    m_m4T: number;
    m_m4U: number;
    m_m5D: number;
    m_m5T: number;
    m_m5U: number;
    m_m6D: number;
    m_m6T: number;
    m_m6U: number;
    m_m1DTot: number;
    m_m1TTot: number;
    m_m1UTot: number;
    m_m2DTot: number;
    m_m2TTot: number;
    m_m2UTot: number;
    m_m3DTot: number;
    m_m3TTot: number;
    m_m3UTot: number;
    m_m4DTot: number;
    m_m4TTot: number;
    m_m4UTot: number;
    m_m5DTot: number;
    m_m5TTot: number;
    m_m5UTot: number;
    m_m6DTot: number;
    m_m6TTot: number;
    m_m6UTot: number;
    currentMonthBudget: number;
    currentMonthBudgetT: number;
    currentMonthBudgetU: number;
    budgetYTD: number;
    budgetYTD_T: number;
    budgetYTD_U: number;
    currentMonthBudgetTot: number;
    currentMonthBudgetTTot: number;
    currentMonthBudgetUTot: number;
    budgetYTDTot: number;
    budgetYTD_TTot: number;
    budgetYTD_UTot: number;
}

export interface SalesInfoDetailParameters {
    args: Args;
    busSalesEnqSrc: BusSalesEnqSrc;
    changeValueBusinessSalesEnq?: string;
    startIndex: number;
    rowCount: number;
}

interface Args {
    rowCount: number;
    startIndex: number;
    orderBy: string;
    additionalParams: string;
    repCode?: string;
}

interface BusSalesEnqSrc {
    cDisplayOption: string;
    sLastFlag: string;
    detailType: string;
    catalogType: string;
    repType: string;
    backeryOption: number;
    iCostPeriod: number;
    sortField: string;
    market: string;
}
