export type Customer = {
  name: string;
  shortName: string;
  company: string;
  business: string;
  leadStatus: string;
  state: string;
  city: string;
  address: string;
  address1: string;
  address2: string;
  postalCode: string;
  telephone: string;
  mobile: string;
  email: string;
  customerCode: string;
  fax: string;
  repCode: string;
  primaryRepName: string;
  secondaryRepName: string;
  leadSource: string;
  industry: string;
  referredBy: string;
  rating: number;
  probability: number;
  website: string;
  noOfEmployees: number;
  annualRevenue: number;
  description: string;
  preferredContact: string;
  businessPotential: string;
  country: string;
  lastCalledDate: Date | null;
  litersBy: string;
  potentialLiters: number;
  status: string;
  modifiedBy: string;
  modifiedDate: Date | null;
  creditStatus: string;
  endUserCode: string;
  custCode: string;
  postcode: string;
  acn: string;
  abn: string;
  gstOverride: number;
  areaCode: string;
  destArea: string;
  internetAdd: string;
  preTradCode: string;
  preTradName: string;
  contact: string;
  type: string;
  parRebateLvl: string;
  priceList: string;
  category: string;
  paymentMethod: string;
  discount: number;
  runNo: string;
  runCode: string;
  runOff: number;
  deliverySequence: number;
  custBusArea: string;
  custMarket: string;
  custGroup: string;
  arGroup: string;
  custSubGroup: string;
  custMarketSubGroup: string;
  priceGroup: string;
  parentCustomer: string;
  startDate: Date | null;
  carrierCode: string;
  freight: string;
  bakeryRepCode: string;
  taxCert: string;
  prevCreditStatus: string;
  payeeNo: string;
  custData: string;
  forCur: string;
  delFlag: string;
  version: number;
  lastStmntDate: Date | null;
  printStmnt: string;
  coa: number;
  ePeerKey: number;
  allocInProgress: string;
  bin1: string;
  bin2: string;
  dispatchmethod: string;
  standradFacilities: string;
  productsServices: string;
  flag: string;
  creditStatusHistory: string;
  siteId: number;
  browseAvailable: string;
  export: string;
  methodOfPay: string;
  mapRef: string;
  copyExportDoc: string;
  gracePeriod: number;
  defWarehouse: string;
  bakRebPerc: number;
  mixedPalletInd: string;
  palletType: string;
  custMarketSubGroupSection: string;
  keyAccount: string;
  splitPlistInd: string;
  rebateMonth: Date | null;
  bulkBinAcc1: string;
  bulkBinAcc2: string;
  bulkBinAcc3: string;
  methodOfDelivery: string;
  tradingTerm: string;
  releaseOrderCount: number;
  correspondance: string;
  sendToPayee: number;
  debtorEmail: string;
  invTerms: number;
  maxDeliveryTime: number;
  isRctiCustomer: number;
  custDesc: string;
  prefContact: string;
  busPotential: string;
  createdBy: string;
  createdDate: Date | null;
  custType: string;
  splitPlist: number;
  deldocEmail: string;
  deliveryHrs: string;
  prevCustCode: string;
  prevCustName: string;
  tioAcceptance: number;
  tiO_Email: string;
  displayInCrm: boolean;
  lastActiveDate: Date | null;
  hideComment: string;
  commentModifiedDate: Date | null;
  grade: string;
  organisationID: number;
  linkId: number;
};

export function createCustomer(): Customer {
  return {
      name: '',
      shortName: '',
      company: '',
      business: '',
      leadStatus: '',
      state: '',
      city: '',
      address: '',
      address1: '',
      address2: '',
      postalCode: '',
      telephone: '',
      mobile: '',
      email: '',
      customerCode: '',
      fax: '',
      repCode: '',
      primaryRepName: '',
      secondaryRepName: '',
      leadSource: '',
      industry: '',
      referredBy: '',
      rating: 0,
      probability: 0,
      website: '',
      noOfEmployees: 0,
      annualRevenue: 0,
      description: '',
      preferredContact: '',
      businessPotential: '',
      country: '',
      lastCalledDate: null,
      litersBy: '',
      potentialLiters: 0,
      status: '',
      modifiedBy: '',
      modifiedDate: null,
      creditStatus: '',
      endUserCode: '',
      custCode: '',
      postcode: '',
      acn: '',
      abn: '',
      gstOverride: 0,
      areaCode: '',
      destArea: '',
      internetAdd: '',
      preTradCode: '',
      preTradName: '',
      contact: '',
      type: '',
      parRebateLvl: '',
      priceList: '',
      category: '',
      paymentMethod: '',
      discount: 0,
      runNo: '',
      runCode: '',
      runOff: 0,
      deliverySequence: 0,
      custBusArea: '',
      custMarket: '',
      custGroup: '',
      arGroup: '',
      custSubGroup: '',
      custMarketSubGroup: '',
      priceGroup: '',
      parentCustomer: '',
      startDate: null,
      carrierCode: '',
      freight: '',
      bakeryRepCode: '',
      taxCert: '',
      prevCreditStatus: '',
      payeeNo: '',
      custData: '',
      forCur: '',
      delFlag: '',
      version: 0,
      lastStmntDate: null,
      printStmnt: '',
      coa: 0,
      ePeerKey: 0,
      allocInProgress: '',
      bin1: '',
      bin2: '',
      dispatchmethod: '',
      standradFacilities: '',
      productsServices: '',
      flag: '',
      creditStatusHistory: '',
      siteId: 0,
      browseAvailable: '',
      export: '',
      methodOfPay: '',
      mapRef: '',
      copyExportDoc: '',
      gracePeriod: 0,
      defWarehouse: '',
      bakRebPerc: 0,
      mixedPalletInd: '',
      palletType: '',
      custMarketSubGroupSection: '',
      keyAccount: '',
      splitPlistInd: '',
      rebateMonth: null,
      bulkBinAcc1: '',
      bulkBinAcc2: '',
      bulkBinAcc3: '',
      methodOfDelivery: '',
      tradingTerm: '',
      releaseOrderCount: 0,
      correspondance: '',
      sendToPayee: 0,
      debtorEmail: '',
      invTerms: 0,
      maxDeliveryTime: 0,
      isRctiCustomer: 0,
      custDesc: '',
      prefContact: '',
      busPotential: '',
      createdBy: '',
      createdDate: null,
      custType: '',
      splitPlist: 0,
      deldocEmail: '',
      deliveryHrs: '',
      prevCustCode: '',
      prevCustName: '',
      tioAcceptance: 0,
      tiO_Email: '',
      displayInCrm: false,
      lastActiveDate: null,
      hideComment: '',
      commentModifiedDate: null,
      grade: '',
      organisationID: 0,
      linkId: 0,
  };
}

