export interface Excel {
    header: string;
    key: string;
    width: number;
}

export const ActivityDataColumns: Excel[] = [
    { header: 'Activity ID', key: 'activityID', width: 15 },
    { header: 'Subject', key: 'subject', width: 20 },
    { header: 'Start Date', key: 'startDate', width: 20 },
    { header: 'End Date', key: 'endDate', width: 20 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Assigned To', key: 'assignedTo', width: 20 },
    { header: 'Lead ID', key: 'leadId', width: 15 },
    { header: 'Comments', key: 'comments', width: 20 },
    { header: 'Sent Mail', key: 'sentMail', width: 15 },
    { header: 'Priority', key: 'priority', width: 15 },
    { header: 'Send Reminder', key: 'sendReminder', width: 15 },
    { header: 'Reminder Date', key: 'reminderDate', width: 20 },
    { header: 'Pipeline Stage ID', key: 'pipelineStageID', width: 20 },
    { header: 'Activity Type', key: 'activityType', width: 15 },
    { header: 'Created Date', key: 'createdDate', width: 20 },
    { header: 'Created By', key: 'createdBy', width: 15 },
    { header: 'Last Modified Date', key: 'lastModifiedDate', width: 20 },
    { header: 'Last Modified By', key: 'lastModifiedBy', width: 15 },
    { header: 'Customer Code', key: 'custCode', width: 20 },
    { header: 'Lead Name', key: 'leadName', width: 20 },
    { header: 'Lead Stage', key: 'leadStage', width: 20 },
    { header: 'Status Description', key: 'statusDesc', width: 20 },
    { header: 'Type Description', key: 'typeDesc', width: 20 },
    { header: 'Number of Activities', key: 'noOfActivities', width: 20 },
    { header: 'Appointment ID', key: 'appointmentId', width: 20 },
    { header: 'Delete Flag', key: 'delFlag', width: 15 },
    { header: 'End User Code', key: 'endUserCode', width: 20 },
    { header: 'Row Count', key: 'rowCount', width: 15 },
    { header: 'Color Code', key: 'colorCode', width: 15 },
    { header: 'Assigned To Name', key: 'assignedToName', width: 20 },
    { header: 'Sample Issued', key: 'sampleIssued', width: 15 },
    { header: 'Sample Feedback Code', key: 'sampleFedbackCode', width: 20 },
    { header: 'Sample Feedback Description', key: 'sampleFedbackDescription', width: 20 },
    { header: 'Turn In Order', key: 'turnInOrder', width: 15 },
    { header: 'Quantity', key: 'quantity', width: 15 },
    { header: 'End User Cust Distributor', key: 'enduserCustDistributor', width: 20 },
    { header: 'Is Dirty', key: 'isDirty', width: 15 },
    { header: 'Is New', key: 'isNew', width: 15 },
    { header: 'Total Count', key: 'totalCount', width: 15 },
    { header: 'Primary Dist', key: 'primaryDist', width: 15 },
]

export const EndUserTransferLogsDataColumns: Excel[] = [
    { header: 'End User Code', key: 'enduserCode', width: 15 },
    { header: 'End User Name', key: 'enduserName', width: 20 },
    { header: 'Transferred On', key: 'transferredOn', width: 20 },
    { header: 'Old Customer', key: 'oldCustomer', width: 20 },
    { header: 'New Customer', key: 'newCustomer', width: 20 },
]

export const OpportunityAnalysisDataColumns: Excel[] = [
    { header: 'Opportunity ID', key: 'opportunityID', width: 15 },
    { header: 'Lead ID', key: 'leadID', width: 15 },
    { header: 'Originator', key: 'originator', width: 15 },
    { header: 'Rep Group ID', key: 'repGroupID', width: 15 },
    { header: 'Rep Group Name', key: 'repGroupName', width: 15 },
    { header: 'Name', key: 'name', width: 15 },
    { header: 'Close Date', key: 'closeDate', width: 15 },
    { header: 'Stage', key: 'stage', width: 15 },
    { header: 'Probability', key: 'probability', width: 15 },
    { header: 'Amount', key: 'amount', width: 15 },
    { header: 'Units', key: 'units', width: 15 },
    { header: 'Description', key: 'description', width: 15 },
    { header: 'Customer Code', key: 'custCode', width: 15 },
    { header: 'Lead Name', key: 'leadName', width: 15 },
    { header: 'Business', key: 'business', width: 15 },
    { header: 'Industry', key: 'industry', width: 15 },
    { header: 'Industry Description', key: 'industryDescription', width: 15 },
    { header: 'Address', key: 'address', width: 15 },
    { header: 'City', key: 'city', width: 15 },
    { header: 'State', key: 'state', width: 15 },
    { header: 'Post Code', key: 'postCode', width: 15 },
    { header: 'Lead Stage', key: 'leadStage', width: 15 },
    { header: 'Pipeline Stage', key: 'pipelineStage', width: 15 },
    { header: 'End User Code', key: 'endUserCode', width: 15 },
    { header: 'Tonnes', key: 'tonnes', width: 15 },
    { header: 'Row Count', key: 'rowCount', width: 15 },
    { header: 'Amount Sum', key: 'amountSum', width: 15 },
    { header: 'Units Sum', key: 'unitsSum', width: 15 },
    { header: 'Tonnes Sum', key: 'tonnesSum', width: 15 },
    { header: 'Is Dirty', key: 'isDirty', width: 15 },
    { header: 'Is New', key: 'isNew', width: 15 },
    { header: 'Total Count', key: 'totalCount', width: 15 },
    { header: 'Created By', key: 'createdBy', width: 15 },
    { header: 'Created Date', key: 'createdDate', width: 15 },
    { header: 'Last Modified By', key: 'lastModifiedBy', width: 15 },
    { header: 'Last Modified Date', key: 'lastModifiedDate', width: 15 },
    { header: 'Primary Distributor', key: 'primaryDist', width: 15 },
];

export const CallCyclesAnalysisDataColumns: Excel[] = [
    { header: 'Item Index', key: 'itemIndex', width: 10 },
    { header: 'Created By', key: 'callCycle.createdBy', width: 15 },
    { header: 'Created Date', key: 'callCycle.createdDate', width: 20 },
    { header: 'Deleted Flag', key: 'callCycle.delFlag', width: 15 },
    { header: 'CC Type', key: 'callCycle.ccType', width: 15 },
    { header: 'Prefix Code', key: 'callCycle.prefixCode', width: 15 },
    { header: 'Call Cycle ID', key: 'callCycle.callCycleID', width: 15 },
    { header: 'Description', key: 'callCycle.description', width: 25 },
    { header: 'Due On', key: 'callCycle.dueOn', width: 20 },
    { header: 'Comments', key: 'callCycle.comments', width: 25 },
    { header: 'No Of Lead Customers', key: 'callCycle.noOfLeadCustomers', width: 20 },
    { header: 'Is Dirty', key: 'callCycle.isDirty', width: 10 },
    { header: 'Is New', key: 'callCycle.isNew', width: 10 },
    { header: 'Total Count', key: 'callCycle.totalCount', width: 15 },
    { header: 'Last Modified By', key: 'callCycle.lastModifiedBy', width: 20 },
    { header: 'Last Modified Date', key: 'callCycle.lastModifiedDate', width: 20 },
    { header: 'Primary Distributor', key: 'callCycle.primaryDist', width: 20 },
    { header: 'Row Count', key: 'callCycle.rowCount', width: 10 },
    { header: 'Contact Source ID', key: 'contact.sourceId', width: 20 },
    { header: 'Contact Name', key: 'contact.name', width: 20 },
    { header: 'Lead Customer Type', key: 'contact.leadCustomerType', width: 20 },
    { header: 'Company', key: 'contact.company', width: 25 },
    { header: 'Business', key: 'contact.business', width: 25 },
    { header: 'Industry', key: 'contact.industry', width: 25 },
    { header: 'Industry Description', key: 'contact.industryDescription', width: 25 },
    { header: 'Lead Status', key: 'contact.leadStatus', width: 20 },
    { header: 'State', key: 'contact.state', width: 10 },
    { header: 'City', key: 'contact.city', width: 15 },
    { header: 'Address', key: 'contact.address', width: 30 },
    { header: 'Address 1', key: 'contact.address1', width: 30 },
    { header: 'Address 2', key: 'contact.address2', width: 30 },
    { header: 'Postal Code', key: 'contact.postalCode', width: 10 },
    { header: 'Telephone', key: 'contact.telephone', width: 20 },
    { header: 'Mobile', key: 'contact.mobile', width: 20 },
    { header: 'Email', key: 'contact.email', width: 25 },
    { header: 'Customer Code', key: 'contact.customerCode', width: 15 },
    { header: 'End User Code', key: 'contact.endUserCode', width: 15 },
    { header: 'Lead Stage', key: 'contact.leadStage', width: 15 },
    { header: 'Fax', key: 'contact.fax', width: 15 },
    { header: 'Lead Source', key: 'contact.leadSource', width: 20 },
    { header: 'Originator', key: 'contact.originator', width: 15 },
    { header: 'Annual Revenue', key: 'contact.annualRevenue', width: 20 },
    { header: 'No Of Employees', key: 'contact.noOfEmployees', width: 15 },
    { header: 'Rating', key: 'contact.rating', width: 10 },
    { header: 'Website', key: 'contact.webiste', width: 25 },
    { header: 'Description', key: 'contact.description', width: 30 },
    { header: 'Business Potential', key: 'contact.businessPotential', width: 20 },
    { header: 'Referred By', key: 'contact.referredBy', width: 20 },
    { header: 'Country', key: 'contact.country', width: 15 },
    { header: 'Preferred Contact', key: 'contact.preferredContact', width: 20 },
    { header: 'Preferred Contact Description', key: 'contact.preferredContactDescription', width: 25 },
    { header: 'Channel Description', key: 'contact.channelDescription', width: 25 },
    { header: 'No Of Lead Customers', key: 'contact.noOfLeadCustomers', width: 20 },
    { header: 'Is Deleted', key: 'contact.isDeleted', width: 10 },
    { header: 'Secondary Rep Code', key: 'contact.secondaryRepCode', width: 20 },
    { header: 'Contact Row Count', key: 'contact.rowCount', width: 10 },
    { header: 'Customer Name', key: 'contact.customerName', width: 25 },
    { header: 'Tonnes', key: 'contact.tonnes', width: 15 },
    { header: 'Dollar', key: 'contact.dollar', width: 15 },
    { header: 'Enrol Date', key: 'contact.enrolDate', width: 20 },
    { header: 'Sales Value', key: 'contact.salesValue', width: 20 },
    { header: 'Sales Date', key: 'contact.salesDate', width: 20 },
    { header: 'Display In CRM', key: 'contact.displayInCrm', width: 10 },
    { header: 'Last Active Date', key: 'contact.lastActiveDate', width: 20 },
    { header: 'Grade', key: 'contact.grade', width: 10 },
    { header: 'Org ID', key: 'contact.orgId', width: 10 },
    { header: 'Org Name', key: 'contact.orgName', width: 25 },
    { header: 'Contact Is Dirty', key: 'contact.isDirty', width: 10 },
    { header: 'Contact Is New', key: 'contact.isNew', width: 10 },
    { header: 'Contact Total Count', key: 'contact.totalCount', width: 15 },
    { header: 'Contact Created By', key: 'contact.createdBy', width: 15 },
    { header: 'Contact Created Date', key: 'contact.createdDate', width: 20 },
    { header: 'Contact Last Modified By', key: 'contact.lastModifiedBy', width: 20 },
    { header: 'Contact Last Modified Date', key: 'contact.lastModifiedDate', width: 20 },
    { header: 'Contact Primary Distributor', key: 'contact.primaryDist', width: 20 },
    { header: 'Originator', key: 'originator', width: 15 },
    { header: 'Lead Stage ID', key: 'leadStage.stageId', width: 10 },
    { header: 'Lead Stage Name', key: 'leadStage.stageName', width: 15 },
    { header: 'Lead Stage Order', key: 'leadStage.stageOrder', width: 10 },
    { header: 'Opportunity Allowed', key: 'leadStage.opportunityAllowed', width: 20 },
    { header: 'Max Opportunities', key: 'leadStage.maxOpportunities', width: 15 },
    { header: 'Lead Stage Email Address', key: 'leadStage.emailAddress', width: 25 },
    { header: 'Lead Type', key: 'leadStage.leadType', width: 15 },
    { header: 'Lead Stage Is New', key: 'leadStage.isNew', width: 10 },
    { header: 'Lead Stage Is Selected', key: 'leadStage.isSelected', width: 10 },
    { header: 'Lead Stage Lead ID', key: 'leadStage.leadStageId', width: 10 },
    { header: 'Lead Stage', key: 'leadStage.leadStage', width: 15 },
    { header: 'Leads Count', key: 'leadStage.leadsCount', width: 10 },
    { header: 'Lead Stage Is Dirty', key: 'leadStage.isDirty', width: 10 },
    { header: 'Lead Stage Total Count', key: 'leadStage.totalCount', width: 15 },
    { header: 'Lead Stage Created By', key: 'leadStage.createdBy', width: 15 },
    { header: 'Lead Stage Created Date', key: 'leadStage.createdDate', width: 20 },
    { header: 'Lead Stage Last Modified By', key: 'leadStage.lastModifiedBy', width: 20 },
    { header: 'Lead Stage Last Modified Date', key: 'leadStage.lastModifiedDate', width: 20 },
    { header: 'Lead Stage Primary Distributor', key: 'leadStage.primaryDist', width: 20 },
    { header: 'Lead Stage Row Count', key: 'leadStage.rowCount', width: 10 },
    { header: 'Week Day ID', key: 'weekDayId', width: 10 },
    { header: 'Due On', key: 'dueOn', width: 20 },
    { header: 'Start Time', key: 'startTime', width: 15 },
    { header: 'Create Activity', key: 'createActivity', width: 15 },
    { header: 'Prefix Code', key: 'prefixCode', width: 15 },
    { header: 'Day Order', key: 'dayOrder', width: 10 },
    { header: 'Is Dirty', key: 'isDirty', width: 10 },
    { header: 'Is New', key: 'isNew', width: 10 },
    { header: 'Total Count', key: 'totalCount', width: 15 },
    { header: 'Created By', key: 'createdBy', width: 15 },
    { header: 'Created Date', key: 'createdDate', width: 20 },
    { header: 'Last Modified By', key: 'lastModifiedBy', width: 20 },
    { header: 'Last Modified Date', key: 'lastModifiedDate', width: 20 },
    { header: 'Primary Distributor', key: 'primaryDist', width: 20 },
    { header: 'Row Count', key: 'rowCount', width: 10 }
];

export const LeaveDataColumns: Excel[] = [
    { header: 'Name', key: 'name', width: 20 },
    { header: 'From Date', key: 'fromDateModified', width: 20 },
    { header: 'To Date', key: 'toDateModified', width: 20 },
    { header: 'Reason', key: 'reason', width: 30 },
    { header: 'Leave Type', key: 'leaveType', width: 20 },
];

